# Generated by Django 6.0.5 on 2026-05-11 00:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date du rapport', unique=True)),
                ('total_sales_count', models.IntegerField(default=0, help_text='Nombre total de ventes')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant total des ventes', max_digits=10)),
                ('total_quantity_sold', models.IntegerField(default=0, help_text='Quantité totale vendue')),
                ('average_sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Prix moyen des ventes', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du rapport')),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'db_table': 'sales_dailyreport',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du produit (ex: Farine de blé 10kg)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du produit')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix unitaire du produit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_in_stock', models.IntegerField(default=0, help_text='Quantité disponible en stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix du jour (peut différer du prix standard)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du produit')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'sales_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('worker', 'Travailleur'), ('client', 'Client/Manager'), ('super_admin', 'Super Administrateur')], default='worker', help_text="Rôle de l'utilisateur dans le système", max_length=20)),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Nombre de tentatives de connexion échouées')),
                ('is_locked', models.BooleanField(default=False, help_text='Compte verrouillé après 3 tentatives échouées')),
                ('last_presence', models.DateTimeField(blank=True, help_text='Dernière présence enregistrée du worker', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('sale', 'Vente enregistrée'), ('invoice', 'Facture créée'), ('price_change', 'Changement de prix'), ('discount_applied', 'Réduction appliquée')], help_text="Type d'action effectuée", max_length=50)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'action")),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP du client', null=True)),
                ('worker', models.ForeignKey(help_text="Worker qui a effectué l'action", limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'db_table': 'sales_activitylog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Pourcentage de réduction (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(help_text='Date de début de la réduction')),
                ('end_date', models.DateTimeField(help_text='Date de fin de la réduction')),
                ('description', models.CharField(blank=True, help_text='Description de la réduction', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la réduction')),
                ('product', models.ForeignKey(help_text='Produit affecté par la réduction', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='sales.product')),
            ],
            options={
                'verbose_name': 'Réduction',
                'verbose_name_plural': 'Réductions',
                'db_table': 'sales_discount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantité vendue', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment de la vente', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Prix total de la vente', max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la vente')),
                ('discount', models.ForeignKey(blank=True, help_text='Réduction appliquée à cette vente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.discount')),
                ('product', models.ForeignKey(help_text='Produit vendu', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.product')),
                ('worker', models.ForeignKey(help_text='Worker qui a enregistré la vente', limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'sales_sale',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Numéro unique de la facture', max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Montant total de la facture', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Montant payé', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', help_text='Statut de la facture', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur la facture')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la facture')),
                ('issued_at', models.DateTimeField(blank=True, help_text="Date d'émission de la facture", null=True)),
                ('worker', models.ForeignKey(help_text='Worker qui a créé la facture', limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ManyToManyField(help_text='Ventes incluses dans cette facture', related_name='invoices', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'sales_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
