"""
Django settings for stock_api project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure the logging directory exists before Django configures logging handlers.
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i5*t+gak98e+xm9fu*qi()&5&rehy+$%)%uh=h318-+ea!kl@_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Jazzmin doit être AVANT django.contrib.admin pour fonctionner
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # Token d'authentification pour l'API
    'sales',  # Application de gestion des ventes
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stock_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==================== CUSTOM USER MODEL ====================
# Utiliser le modèle utilisateur personnalisé
AUTH_USER_MODEL = 'sales.CustomUser'


# ==================== REST FRAMEWORK CONFIGURATION ====================
REST_FRAMEWORK = {
    # ===== AUTHENTIFICATION =====
    # Les utilisateurs doivent être authentifiés pour accéder à l'API
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    
    # ===== PERMISSIONS =====
    # Par défaut, seuls les utilisateurs authentifiés ont accès
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # ===== PAGINATION =====
    # Paginer les résultats de liste
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # ===== FILTRAGE =====
    # Activer le filtrage et la recherche
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    
    # ===== THROTTLING (Limitation de débit) =====
    # Protéger l'API contre les abus
    'DEFAULT_THROTTLE_CLASSES': [
        'sales.throttling.UserRateThrottle_10_Per_Minute',
        'sales.throttling.AnonRateThrottle_5_Per_Minute',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user_10_per_minute': '10/minute',
        'anon_5_per_minute': '5/minute',
        'user_100_per_hour': '100/hour',
        'login_attempt': '5/15minutes',
        'registration_attempt': '10/hour',
        'api_abuse': '1000/hour',
        'price_change': '50/hour',
        'discount_creation': '30/hour',
        'sale_creation': '500/hour',
    },
    
    # ===== FORMAT =====
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# ==================== JAZZMIN CONFIGURATION ====================
# Configuration pour l'interface admin Jazzmin (meilleure apparence)
JAZZMIN_SETTINGS = {
    "site_title": "Stock API Admin",
    "site_header": "Gestion des Ventes - Interface d'Administration",
    "site_brand": "Stock API",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "favicon": None,
    
    # Apparence générale
    "show_sidebar": True,
    "navigation_expanded": True,
    "navigation_background": "#2c3e50",
    "navigation_color": "#ecf0f1",
    
    # Boutons et couleurs
    "use_google_fonts_cdn": True,
    "show_search_bar": True,
    "show_ui_builder": False,
    
    # Personnalisations des modèles
    "order": [
        "sales",
        "sales.CustomUser",
        "sales.Product",
        "sales.Sale",
        "sales.Invoice",
        "sales.Discount",
        "sales.ActivityLog",
        "sales.DailyReport",
        "auth",
        "auth.User",
        "auth.Group",
    ],
    
    # Paramètres d'interface
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "sales.CustomUser": "fas fa-user-tie",
        "sales.Product": "fas fa-cube",
        "sales.Sale": "fas fa-shopping-cart",
        "sales.Invoice": "fas fa-file-invoice",
        "sales.Discount": "fas fa-tag",
        "sales.ActivityLog": "fas fa-history",
        "sales.DailyReport": "fas fa-chart-bar",
    },
}

# Thème Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_admin_site_header": False,
    "menu_show_lineitems": False,
}


# ==================== SÉCURITÉ ====================
# Configuration de sécurité pour protéger contre les injections SQL et autres attaques

# 1. Protection contre les injections SQL
# Django utilise les paramètres liés (parameterized queries) par défaut
# qui protègent automatiquement contre les injections SQL

# 2. Protection CSRF (Cross-Site Request Forgery)
CSRF_COOKIE_SECURE = False  # À mettre à True en production (requiert HTTPS)
CSRF_COOKIE_HTTPONLY = True  # Ne pas exposer le cookie CSRF en JavaScript

# 3. Protection de sécurité HTTP
SECURE_BROWSER_XSS_FILTER = True  # Protéger contre les attaques XSS
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'",),
    "style-src": ("'self'", "'unsafe-inline'"),
    "img-src": ("'self'", "data:", "https:"),
}

# 4. Protection des cookies
SESSION_COOKIE_SECURE = False  # À mettre à True en production (requiert HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Ne pas exposer le cookie de session en JavaScript
SESSION_COOKIE_AGE = 86400  # 24 heures en secondes

# 5. Authentification Token
# Les tokens expirent après 30 jours d'inactivité (peut être modifié)
RESET_TOKEN_EXPIRE_DAYS = 7  # Délai d'expiration du token

# 6. Hashage des mots de passe
# Utiliser PBKDF2 avec SHA256 (configuré par défaut dans Django)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# ==================== LOGGING ====================
# Configuration pour enregistrer les erreurs et les événements
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'sales': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

